# This rule is not used by the project titan-scheduler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the batch.rory109.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: titan-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: trainingjob-editor-role
rules:
- apiGroups:
  - batch.rory109.com
  resources:
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.rory109.com
  resources:
  - trainingjobs/status
  verbs:
  - get
