# This rule is not used by the project titan-scheduler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.rory109.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: titan-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: trainingjob-admin-role
rules:
- apiGroups:
  - batch.rory109.com
  resources:
  - trainingjobs
  verbs:
  - '*'
- apiGroups:
  - batch.rory109.com
  resources:
  - trainingjobs/status
  verbs:
  - get
